### ISSUE TITLE
Is storybuilder still available?

### ISSUE THREAD

**Issue by marineb** [alexbredy/storybuilder#1]
Hi, I was wondering if your code is still available somewhere? I would have loved to see what it does. 

Thanks, 
Marine

**Comment by alexbredy** [comment]
Hi Marine,

Apologies for the intergalactic delay in getting back to you! The code has finally been added to the repository. You can launch the web app by opening the Storybuilder.html file.

Best regards,
Alex

**Comment by marineb** [comment]
Just saw this. Thank you!
